#!/bin/bash

# 显示菜单
echo "欢迎使用Java程序启动菜单"
echo "请输入选项："
echo "1. 配置Java程序"
echo "2. 退出"

# 读取用户输入
read -p "请输入选项（1-2）：" option

# 根据用户输入执行相应操作
case $option in
    1)
        # 提示用户输入Java程序的jar文件路径
        read -p "请输入jar文件路径 已安装的有: 
$(ls /usr/lib/jvm/*/bin/java) :"
        
        # 提示用户输入Java程序的最小内存
        read -p "请输入Java程序的最小内存（例如：512m,2G）：" min_memory
        
        # 提示用户输入Java程序的最大内存
        read -p "请输入Java程序的最大内存（例如：1024m,2G）：" max_memory
        
        # 合成并执行java -jar命令
        echo -e "
        cd ${HOME}/.gancm/MCserver/${Download_MC_SERVER_class_menu[$((user_choice_Download_MC_SERVER_class_menu-1))]}/${Download_MC_SERVER_versions_menu[$((user_choice_Download_MC_SERVER_versions_menu_list_names - 1))]}
        echo -e "eula=true" > ${HOME}/.gancm/MCserver/${Download_MC_SERVER_class_menu[$((user_choice_Download_MC_SERVER_class_menu-1))]}/${Download_MC_SERVER_versions_menu[$((user_choice_Download_MC_SERVER_versions_menu_list_names - 1))]}/eula.txt
        java -Xms"$min_memory" -Xmx"$max_memory" -jar "${HOME}/.gancm/MCserver/${Download_MC_SERVER_class_menu[$((user_choice_Download_MC_SERVER_class_menu-1))]}/${Download_MC_SERVER_versions_menu[$((user_choice_Download_MC_SERVER_versions_menu_list_names - 1))]}/${Download_MC_SERVER_class_menu[$((user_choice_Download_MC_SERVER_class_menu-1))]}_${Download_MC_SERVER_versions_menu[$((user_choice_Download_MC_SERVER_versions_menu_list_names - 1))]}_server.jar" 
        
        " > ${HOME}/.gancm/MCserver/${Download_MC_SERVER_class_menu[$((user_choice_Download_MC_SERVER_class_menu-1))]}/${Download_MC_SERVER_versions_menu[$((user_choice_Download_MC_SERVER_versions_menu_list_names - 1))]}/start.sh
        ;;
    2)
        echo "退出程序"
        exit 0
        ;;
    *)
        echo "无效的选项，请重新运行脚本并选择1或2。"
        ;;
esac



